spring:
  application:
    name: persistor-service
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
topic:
  trade:
    name: trades
