server:
  port: 8088

spring:
  application:
    name: config-service
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.config: DEBUG