spring:
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

webSocket:
  uri: wss://stream.binance.com:9443/ws/btcusdt@trade

management:
  endpoints:
    web:
      exposure:
        include: health

topic:
  trade:
    name: trades
