spring:
  application:
    name: ingestor-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      fail-fast: true

  config:
    import: "optional:configserver:"

